In [101]:
import pandas as pd
import numpy as np
import pickle
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [102]:
career = pd.read_csv('/content/drive/My Drive/BE Project/dataset9000.csv')

In [103]:
X = np.array(career.iloc[:, 0:17]) #X is skills
print(X)
y = np.array(career.iloc[:, 17]) #Y is Roles

[['Professional' 'Not Interested' 'Not Interested' ... 'Not Interested'
  'Not Interested' 'Not Interested']
 ['Professional' 'Poor' 'Not Interested' ... 'Not Interested'
  'Not Interested' 'Not Interested']
 ['Professional' 'Beginner' 'Not Interested' ... 'Not Interested'
  'Not Interested' 'Not Interested']
 ...
 ['Not Interested' 'Not Interested' 'Not Interested' ... 'Average'
  'Average' 'Professional']
 ['Not Interested' 'Not Interested' 'Not Interested' ... 'Intermediate'
  'Intermediate' 'Professional']
 ['Not Interested' 'Not Interested' 'Not Interested' ... 'Excellent'
  'Excellent' 'Professional']]


In [104]:
career.columns = ["Database Fundamentals","Computer Architecture","Distributed Computing Systems",
"Cyber Security","Networking","Development","Programming Skills","Project Management",
"Computer Forensics Fundamentals","Technical Communication","AI ML","Software Engineering","Business Analysis",
"Communication skills","Data Science","Troubleshooting skills","Graphics Designing","Roles"]

In [105]:
career.dropna(how ='all', inplace = True)

In [106]:
career.head()

Database Fundamentals Computer Architecture Distributed Computing Systems  \
0          Professional        Not Interested                Not Interested   
1          Professional                  Poor                Not Interested   
2          Professional              Beginner                Not Interested   
3          Professional               Average                Not Interested   
4          Professional          Intermediate                Not Interested   

   Cyber Security      Networking     Development Programming Skills  \
0  Not Interested  Not Interested  Not Interested     Not Interested   
1  Not Interested  Not Interested  Not Interested     Not Interested   
2  Not Interested  Not Interested  Not Interested     Not Interested   
3  Not Interested  Not Interested  Not Interested     Not Interested   
4  Not Interested  Not Interested  Not Interested     Not Interested   

  Project Management Computer Forensics Fundamentals Technical Communication  \
0     Not Interested                  Not Interested          Not Interested   
1     Not Interested                  Not Interested          Not Interested   
2     Not Interested                  Not Interested          Not Interested   
3     Not Interested                  Not Interested          Not Interested   
4     Not Interested                  Not Interested          Not Interested   

            AI ML Software Engineering Business Analysis Communication skills  \
0  Not Interested       Not Interested    Not Interested       Not Interested   
1  Not Interested       Not Interested    Not Interested       Not Interested   
2  Not Interested       Not Interested    Not Interested       Not Interested   
3  Not Interested       Not Interested    Not Interested       Not Interested   
4  Not Interested       Not Interested    Not Interested       Not Interested   

     Data Science Troubleshooting skills Graphics Designing  \
0  Not Interested         Not Interested     Not Interested   
1  Not Interested         Not Interested     Not Interested   
2  Not Interested         Not Interested     Not Interested   
3  Not Interested         Not Interested     Not Interested   
4  Not Interested         Not Interested     Not Interested   

                    Roles  
0  Database Administrator  
1  Database Administrator  
2  Database Administrator  
3  Database Administrator  
4  Database Administrator

In [107]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3, random_state = 524)

In [108]:
career.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9179 entries, 0 to 9178
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   Database Fundamentals            9179 non-null   object
 1   Computer Architecture            9179 non-null   object
 2   Distributed Computing Systems    9179 non-null   object
 3   Cyber Security                   9179 non-null   object
 4   Networking                       9179 non-null   object
 5   Development                      9179 non-null   object
 6   Programming Skills               9179 non-null   object
 7   Project Management               9179 non-null   object
 8   Computer Forensics Fundamentals  9179 non-null   object
 9   Technical Communication          9179 non-null   object
 10  AI ML                            9179 non-null   object
 11  Software Engineering             9179 non-null   object
 12  Business Analysis                9

In [109]:
career.describe()

Database Fundamentals Computer Architecture  \
count                   9179                  9179   
unique                     7                     7   
top           Not Interested        Not Interested   
freq                    1440                  1440   

       Distributed Computing Systems  Cyber Security      Networking  \
count                           9179            9179            9179   
unique                             7               7               7   
top                   Not Interested  Not Interested  Not Interested   
freq                            1440            1440            1440   

           Development Programming Skills Project Management  \
count             9179               9179               9179   
unique               7                  7                  7   
top     Not Interested     Not Interested     Not Interested   
freq              1440               1440               1440   

       Computer Forensics Fundamentals Technical Communication  \
count                             9179                    9179   
unique                               7                       7   
top                     Not Interested          Not Interested   
freq                              1440                    1440   

                 AI ML Software Engineering Business Analysis  \
count             9179                 9179              9179   
unique               7                    7                 7   
top     Not Interested       Not Interested    Not Interested   
freq              1440                 1440              1440   

       Communication skills    Data Science Troubleshooting skills  \
count                  9179            9179                   9179   
unique                    7               7                      7   
top          Not Interested  Not Interested         Not Interested   
freq                   1440            1440                   1440   

       Graphics Designing                   Roles  
count                9178                    9179  
unique                  7                      17  
top        Not Interested  Database Administrator  
freq                 1440                     540

In [110]:
career['Roles'].value_counts()

Roles
Database Administrator             540
Technical Writer                   540
Helpdesk Engineer                  540
Data Scientist                     540
Customer Service Executive         540
Business Analyst                   540
Software tester                    540
AI ML Specialist                   540
Information Security Specialist    540
Hardware Engineer                  540
Project Manager                    540
API Specialist                     540
Software Developer                 540
Networking Engineer                540
Cyber Security Specialist          540
Application Support Engineer       540
Graphics Designer                  539
Name: count, dtype: int64

In [111]:
career['Networking'].value_counts()

Networking
Not Interested    1440
Poor              1440
Beginner          1440
Average           1440
Intermediate      1440
Excellent         1439
Professional       540
Name: count, dtype: int64

In [112]:
label_mapping = {
    'Not Interested' : 0,
    'Poor'           : 1,
    'Beginner'       : 2,
    'Average'        : 3,
    'Intermediate'   : 4,
    'Excellent'     : 5 ,
    'Professional'  : 6,

  }

In [113]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [114]:
labelencoder = LabelEncoder()

In [115]:
labelencoder.fit(career["Roles"])

LabelEncoder()

In [116]:
career["Roles"] = labelencoder.transform(career["Roles"])

In [117]:
career.head()

Database Fundamentals Computer Architecture Distributed Computing Systems  \
0          Professional        Not Interested                Not Interested   
1          Professional                  Poor                Not Interested   
2          Professional              Beginner                Not Interested   
3          Professional               Average                Not Interested   
4          Professional          Intermediate                Not Interested   

   Cyber Security      Networking     Development Programming Skills  \
0  Not Interested  Not Interested  Not Interested     Not Interested   
1  Not Interested  Not Interested  Not Interested     Not Interested   
2  Not Interested  Not Interested  Not Interested     Not Interested   
3  Not Interested  Not Interested  Not Interested     Not Interested   
4  Not Interested  Not Interested  Not Interested     Not Interested   

  Project Management Computer Forensics Fundamentals Technical Communication  \
0     Not Interested                  Not Interested          Not Interested   
1     Not Interested                  Not Interested          Not Interested   
2     Not Interested                  Not Interested          Not Interested   
3     Not Interested                  Not Interested          Not Interested   
4     Not Interested                  Not Interested          Not Interested   

            AI ML Software Engineering Business Analysis Communication skills  \
0  Not Interested       Not Interested    Not Interested       Not Interested   
1  Not Interested       Not Interested    Not Interested       Not Interested   
2  Not Interested       Not Interested    Not Interested       Not Interested   
3  Not Interested       Not Interested    Not Interested       Not Interested   
4  Not Interested       Not Interested    Not Interested       Not Interested   

     Data Science Troubleshooting skills Graphics Designing  Roles  
0  Not Interested         Not Interested     Not Interested      7  
1  Not Interested         Not Interested     Not Interested      7  
2  Not Interested         Not Interested     Not Interested      7  
3  Not Interested         Not Interested     Not Interested      7  
4  Not Interested         Not Interested     Not Interested      7

In [118]:
column_names = career.columns.tolist()
print(column_names)

['Database Fundamentals', 'Computer Architecture', 'Distributed Computing Systems', 'Cyber Security', 'Networking', 'Development', 'Programming Skills', 'Project Management', 'Computer Forensics Fundamentals', 'Technical Communication', 'AI ML', 'Software Engineering', 'Business Analysis', 'Communication skills', 'Data Science', 'Troubleshooting skills', 'Graphics Designing', 'Roles']


In [119]:
for column in column_names:
    labelencoder.fit(career[column])

    # Transform the data in the column using the fitted LabelEncoder
    career[column] = labelencoder.transform(career[column])

In [120]:
career.head()

Database Fundamentals  Computer Architecture  \
0                      6                      4   
1                      6                      5   
2                      6                      1   
3                      6                      0   
4                      6                      3   

   Distributed Computing Systems  Cyber Security  Networking  Development  \
0                              4               4           4            4   
1                              4               4           4            4   
2                              4               4           4            4   
3                              4               4           4            4   
4                              4               4           4            4   

   Programming Skills  Project Management  Computer Forensics Fundamentals  \
0                   4                   4                                4   
1                   4                   4                                4   
2                   4                   4                                4   
3                   4                   4                                4   
4                   4                   4                                4   

   Technical Communication  AI ML  Software Engineering  Business Analysis  \
0                        4      4                     4                  4   
1                        4      4                     4                  4   
2                        4      4                     4                  4   
3                        4      4                     4                  4   
4                        4      4                     4                  4   

   Communication skills  Data Science  Troubleshooting skills  \
0                     4             4                       4   
1                     4             4                       4   
2                     4             4                       4   
3                     4             4                       4   
4                     4             4                       4   

   Graphics Designing  Roles  
0                   4      7  
1                   4      7  
2                   4      7  
3                   4      7  
4                   4      7

In [121]:
X = np.array(career.iloc[:, 0:17]) #X is skills
print(X)
y = np.array(career.iloc[:, 17]) #Y is Roles

[[6 4 4 ... 4 4 4]
 [6 5 4 ... 4 4 4]
 [6 1 4 ... 4 4 4]
 ...
 [4 4 4 ... 0 0 6]
 [4 4 4 ... 3 3 6]
 [4 4 4 ... 2 2 6]]


In [122]:
print(X)

[[6 4 4 ... 4 4 4]
 [6 5 4 ... 4 4 4]
 [6 1 4 ... 4 4 4]
 ...
 [4 4 4 ... 0 0 6]
 [4 4 4 ... 3 3 6]
 [4 4 4 ... 2 2 6]]


In [123]:
print(y)

[7 7 7 ... 8 8 8]


In [124]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [125]:
scores = {}
knn = KNeighborsClassifier(n_neighbors=5)

In [126]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3, random_state = 524)

In [127]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [128]:
print('X_train',X_train)

X_train [[1 1 1 ... 1 1 6]
 [0 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 1 1 1]
 [4 4 4 ... 4 4 4]
 [5 6 5 ... 5 3 3]]


In [129]:

print('y_train',y_train)

y_train [ 8  4  7 ... 14  0  9]


In [130]:
y_pred = knn.predict(X_test)

In [131]:
scores[5] = metrics.accuracy_score(y_test, y_pred)
print('Accuracy=',scores[5]*100)

Accuracy= 90.34132171387074


In [132]:
pickle.dump(knn, open('careerlast.pkl','wb'))
print('test file created')

test file created


In [133]:
#Decision Tree Classifier

from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score

In [134]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [135]:
DT_model = tree.DecisionTreeClassifier()
DT_model = DT_model.fit(X_train, y_train)
DT_model

DecisionTreeClassifier()

In [136]:
DT_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [137]:
y_pred = DT_model.predict(X_test)

In [138]:
scores[6] = metrics.accuracy_score(y_test, y_pred)
print('Accuracy=',scores[6]*100)

Accuracy= 100.0
